name: Deploy Demo to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
      
  workflow_dispatch:
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@master
        with:
          node-version: '14.15'
          
      - run: npm install && npm run build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUIZPPA_COM }}'
          channelId: live
          projectId: luizppa-com
          target: ghcontributions
