name: Publish update to NPM

on: 
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '14.15'

      - run: npm install && npm install -g @angular/cli && ng build --prod ng-github-contributions

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/ng-github-contributions/package.json
